// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	rabbitmq "github.com/hoag/go-social-feed/internal/delivery/rabbitmq"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Producer) Close() {
	_m.Called()
}

// PublishDeletePostRelationMsg provides a mock function with given fields: ctx, msg
func (_m *Producer) PublishDeletePostRelationMsg(ctx context.Context, msg rabbitmq.DeletePostRelationMsg) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishDeletePostRelationMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rabbitmq.DeletePostRelationMsg) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishNotiMsg provides a mock function with given fields: ctx, msg
func (_m *Producer) PublishNotiMsg(ctx context.Context, msg rabbitmq.PublishNotiMsg) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishNotiMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rabbitmq.PublishNotiMsg) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with no fields
func (_m *Producer) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
