export const fallbackDescriptions: Record<string, string> = {
    "btc": "Bitcoin là tiền điện tử đầu tiên và phổ biến nhất trên thế giới, được tạo ra vào năm 2009 bởi một nhân vật hoặc nhóm người ẩn danh tên là Satoshi Nakamoto.\n\nBitcoin hoạt động trên công nghệ blockchain, cho phép giao dịch ngang hàng (P2P) mà không cần qua trung gian như ngân hàng. Với nguồn cung giới hạn 21 triệu đồng, Bitcoin thường được ví như 'vàng kỹ thuật số' và là tài sản lưu trữ giá trị hàng đầu trong thị trường crypto.",
    "eth": "Ethereum là một nền tảng blockchain mã nguồn mở cho phép các nhà phát triển xây dựng và triển khai các ứng dụng phi tập trung (dApps) và hợp đồng thông minh (Smart Contracts). Đồng tiền mã hóa gốc của mạng lưới là Ether (ETH).\n\nKhác với Bitcoin, Ethereum không chỉ là tiền tệ mà còn là một nền tảng lập trình toàn cầu, đặt nền móng cho tài chính phi tập trung (DeFi) và NFT.",
    "bnb": "BNB (Binance Coin) là đồng tiền mã hóa gốc của hệ sinh thái Binance, bao gồm sàn giao dịch Binance và Binance Smart Chain (BSC).\n\nBan đầu là một token ERC-20 trên Ethereum, BNB đã chuyển sang blockchain riêng của mình. BNB được sử dụng để giảm phí giao dịch trên sàn Binance, tham gia bán token (Launchpad), và thanh toán phí gas trên mạng lưới BSC.",
    "sol": "Solana là một nền tảng blockchain hiệu suất cao, được thiết kế để hỗ trợ các ứng dụng phi tập trung (dApps) và tiền điện tử với tốc độ giao dịch cực nhanh và chi phí thấp.\n\nNhờ cơ chế đồng thuận Proof of History (PoH) độc đáo kết hợp với Proof of Stake (PoS), Solana có thể xử lý hàng nghìn giao dịch mỗi giây mà không cần sharding, làm cho nó trở thành đối thủ đáng gờm của Ethereum.",
    "xrp": "XRP là đồng tiền kỹ thuật số được phát triển bởi Ripple Labs, được thiết kế để tạo điều kiện cho các giao dịch chuyển tiền quốc tế nhanh chóng và rẻ tiền.\n\nKhác với Bitcoin, XRP không dựa vào đào (mining) mà sử dụng cơ chế đồng thuận riêng. Ripple chủ yếu nhắm đến việc phục vụ các ngân hàng và tổ chức tài chính để cải thiện hệ thống thanh toán xuyên biên giới.",
    "ada": "Cardano là một nền tảng blockchain thế hệ thứ ba, sử dụng cơ chế đồng thuận Proof of Stake (PoS) có tên là Ouroboros.\n\nĐược sáng lập bởi Charles Hoskinson (đồng sáng lập Ethereum), Cardano hướng đến việc giải quyết các vấn đề về khả năng mở rộng, khả năng tương tác và tính bền vững mà các blockchain thế hệ trước gặp phải. Token gốc của mạng lưới là ADA.",
    "doge": "Dogecoin là một loại tiền điện tử ngang hàng mã nguồn mở, ban đầu được tạo ra như một trò đùa (meme coin) dựa trên meme 'Doge' nổi tiếng.\n\nTuy nhiên, nhờ cộng đồng ủng hộ mạnh mẽ và phí giao dịch thấp, Dogecoin đã trở thành một phương tiện thanh toán phổ biến cho các giao dịch nhỏ và tipping trực tuyến. Elon Musk là một trong những người ủng hộ nổi tiếng nhất của Dogecoin."
};
