// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/hoag/go-social-feed/internal/models"
	mock "github.com/stretchr/testify/mock"

	paginator "github.com/hoag/go-social-feed/pkg/paginator"

	repository "github.com/hoag/go-social-feed/internal/post/repository"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) Create(ctx context.Context, sc models.Scope, opts repository.CreateOptions) (models.Post, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.CreateOptions) (models.Post, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.CreateOptions) models.Post); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.CreateOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateComment provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) CreateComment(ctx context.Context, sc models.Scope, opts repository.CreateCommentOptions) (models.Comment, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.CreateCommentOptions) (models.Comment, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.CreateCommentOptions) models.Comment); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.CreateCommentOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateReaction provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) CreateReaction(ctx context.Context, sc models.Scope, opts repository.CreateReactionOptions) (models.Reaction, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateReaction")
	}

	var r0 models.Reaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.CreateReactionOptions) (models.Reaction, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.CreateReactionOptions) models.Reaction); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		r0 = ret.Get(0).(models.Reaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.CreateReactionOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, sc, id
func (_m *Repository) Delete(ctx context.Context, sc models.Scope, id string) error {
	ret := _m.Called(ctx, sc, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) error); ok {
		r0 = rf(ctx, sc, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, sc, id
func (_m *Repository) DeleteComment(ctx context.Context, sc models.Scope, id string) error {
	ret := _m.Called(ctx, sc, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) error); ok {
		r0 = rf(ctx, sc, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteReaction provides a mock function with given fields: ctx, sc, id
func (_m *Repository) DeleteReaction(ctx context.Context, sc models.Scope, id string) error {
	ret := _m.Called(ctx, sc, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) error); ok {
		r0 = rf(ctx, sc, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Detail provides a mock function with given fields: ctx, sc, id
func (_m *Repository) Detail(ctx context.Context, sc models.Scope, id string) (models.Post, error) {
	ret := _m.Called(ctx, sc, id)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) (models.Post, error)); ok {
		return rf(ctx, sc, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) models.Post); ok {
		r0 = rf(ctx, sc, id)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, string) error); ok {
		r1 = rf(ctx, sc, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailComment provides a mock function with given fields: ctx, sc, id
func (_m *Repository) DetailComment(ctx context.Context, sc models.Scope, id string) (models.Comment, error) {
	ret := _m.Called(ctx, sc, id)

	if len(ret) == 0 {
		panic("no return value specified for DetailComment")
	}

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) (models.Comment, error)); ok {
		return rf(ctx, sc, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) models.Comment); ok {
		r0 = rf(ctx, sc, id)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, string) error); ok {
		r1 = rf(ctx, sc, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailReaction provides a mock function with given fields: ctx, sc, id
func (_m *Repository) DetailReaction(ctx context.Context, sc models.Scope, id string) (models.Reaction, error) {
	ret := _m.Called(ctx, sc, id)

	if len(ret) == 0 {
		panic("no return value specified for DetailReaction")
	}

	var r0 models.Reaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) (models.Reaction, error)); ok {
		return rf(ctx, sc, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, string) models.Reaction); ok {
		r0 = rf(ctx, sc, id)
	} else {
		r0 = ret.Get(0).(models.Reaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, string) error); ok {
		r1 = rf(ctx, sc, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) Get(ctx context.Context, sc models.Scope, opts repository.GetOptions) ([]models.Post, paginator.Paginator, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []models.Post
	var r1 paginator.Paginator
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetOptions) ([]models.Post, paginator.Paginator, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetOptions) []models.Post); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.GetOptions) paginator.Paginator); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Get(1).(paginator.Paginator)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.Scope, repository.GetOptions) error); ok {
		r2 = rf(ctx, sc, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetComment provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) GetComment(ctx context.Context, sc models.Scope, opts repository.GetCommentOptions) ([]models.Comment, paginator.Paginator, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetComment")
	}

	var r0 []models.Comment
	var r1 paginator.Paginator
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetCommentOptions) ([]models.Comment, paginator.Paginator, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetCommentOptions) []models.Comment); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.GetCommentOptions) paginator.Paginator); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Get(1).(paginator.Paginator)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.Scope, repository.GetCommentOptions) error); ok {
		r2 = rf(ctx, sc, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetOneComment provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) GetOneComment(ctx context.Context, sc models.Scope, opts repository.GetOneCommentOptions) (models.Comment, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetOneComment")
	}

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetOneCommentOptions) (models.Comment, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetOneCommentOptions) models.Comment); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.GetOneCommentOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReaction provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) GetReaction(ctx context.Context, sc models.Scope, opts repository.GetReactionOptions) ([]models.Reaction, paginator.Paginator, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetReaction")
	}

	var r0 []models.Reaction
	var r1 paginator.Paginator
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetReactionOptions) ([]models.Reaction, paginator.Paginator, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.GetReactionOptions) []models.Reaction); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.GetReactionOptions) paginator.Paginator); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Get(1).(paginator.Paginator)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.Scope, repository.GetReactionOptions) error); ok {
		r2 = rf(ctx, sc, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) List(ctx context.Context, sc models.Scope, opts repository.ListOptions) ([]models.Post, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.ListOptions) ([]models.Post, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.ListOptions) []models.Post); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.ListOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListComment provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) ListComment(ctx context.Context, sc models.Scope, opts repository.ListCommentOptions) ([]models.Comment, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListComment")
	}

	var r0 []models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.ListCommentOptions) ([]models.Comment, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.ListCommentOptions) []models.Comment); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.ListCommentOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReaction provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) ListReaction(ctx context.Context, sc models.Scope, opts repository.ListReactionOptions) ([]models.Reaction, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListReaction")
	}

	var r0 []models.Reaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.ListReactionOptions) ([]models.Reaction, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.ListReactionOptions) []models.Reaction); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.ListReactionOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) Update(ctx context.Context, sc models.Scope, opts repository.UpdateOptions) error {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.UpdateOptions) error); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateComment provides a mock function with given fields: ctx, sc, opts
func (_m *Repository) UpdateComment(ctx context.Context, sc models.Scope, opts repository.UpdateCommentOptions) (models.Comment, error) {
	ret := _m.Called(ctx, sc, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.UpdateCommentOptions) (models.Comment, error)); ok {
		return rf(ctx, sc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Scope, repository.UpdateCommentOptions) models.Comment); ok {
		r0 = rf(ctx, sc, opts)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Scope, repository.UpdateCommentOptions) error); ok {
		r1 = rf(ctx, sc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
